import jsPDF from "jspdf";

export function downloadInvoicePDF(invoice) {
  const doc = new jsPDF();
  const w = doc.internal.pageSize.getWidth();

  // Header
  doc.setFontSize(20);
  doc.setTextColor(79, 70, 229); // indigo
  doc.text("Rehab", 20, 25);
  doc.setTextColor(249, 115, 22); // orange
  doc.text("Flow", 20 + doc.getTextWidth("Rehab"), 25);

  doc.setFontSize(9);
  doc.setTextColor(120, 120, 120);
  doc.text("1200 Wellness Blvd, Suite 300", 20, 32);
  doc.text("care@rehabflow.app · (555) 234-5678", 20, 37);

  // Invoice label
  doc.setFontSize(14);
  doc.setTextColor(30, 30, 30);
  doc.text("INVOICE", w - 20, 25, { align: "right" });
  doc.setFontSize(9);
  doc.setTextColor(120, 120, 120);
  doc.text(invoice.id || "", w - 20, 32, { align: "right" });
  doc.text(invoice.date || new Date().toLocaleDateString(), w - 20, 37, { align: "right" });

  // Divider
  doc.setDrawColor(220, 220, 220);
  doc.line(20, 42, w - 20, 42);

  // Patient
  doc.setFontSize(11);
  doc.setTextColor(30, 30, 30);
  doc.text(`Patient: ${invoice.patient || ""}`, 20, 52);

  // Table header
  const tableY = 62;
  doc.setFillColor(245, 245, 250);
  doc.rect(20, tableY - 5, w - 40, 10, "F");
  doc.setFontSize(9);
  doc.setFont(undefined, "bold");
  doc.setTextColor(80, 80, 80);
  doc.text("Package", 22, tableY);
  doc.text("Sessions", 85, tableY, { align: "center" });
  doc.text("Price/Session", 125, tableY, { align: "center" });
  doc.text("Subtotal", w - 22, tableY, { align: "right" });

  // Table row
  const rowY = tableY + 12;
  doc.setFont(undefined, "normal");
  doc.setTextColor(50, 50, 50);
  doc.setFontSize(10);
  doc.text(invoice.pkg || invoice.package || "", 22, rowY);
  doc.text(String(invoice.sessions || ""), 85, rowY, { align: "center" });
  doc.text(`$${invoice.pricePerSession || invoice.amount || 0}`, 125, rowY, { align: "center" });
  doc.text(`$${invoice.subtotal || invoice.amount || 0}`, w - 22, rowY, { align: "right" });

  doc.setDrawColor(230, 230, 230);
  doc.line(20, rowY + 4, w - 20, rowY + 4);

  let currentY = rowY + 14;

  // Discount
  if (invoice.discountPct && invoice.discountPct > 0) {
    doc.setFontSize(9);
    doc.setTextColor(120, 120, 120);
    doc.text(`Discount (${invoice.discountPct}%): -$${invoice.discountAmt?.toFixed(2) || "0.00"}`, w - 22, currentY, { align: "right" });
    currentY += 8;
  }

  // Total
  doc.setFontSize(14);
  doc.setFont(undefined, "bold");
  doc.setTextColor(30, 30, 30);
  const total = invoice.total ?? invoice.amount ?? 0;
  doc.text(`Total: $${typeof total === "number" ? total.toFixed(2) : total}`, w - 22, currentY, { align: "right" });

  // Notes
  if (invoice.notes) {
    currentY += 12;
    doc.setDrawColor(230, 230, 230);
    doc.line(20, currentY, w - 20, currentY);
    currentY += 8;
    doc.setFontSize(8);
    doc.setFont(undefined, "normal");
    doc.setTextColor(140, 140, 140);
    doc.text(`Notes: ${invoice.notes}`, 20, currentY, { maxWidth: w - 40 });
  }

  // Footer
  doc.setFontSize(7);
  doc.setTextColor(180, 180, 180);
  doc.text("Generated by RehabFlow — rehabflow.app", w / 2, 280, { align: "center" });

  doc.save(`${invoice.id || "invoice"}.pdf`);
}
